version: '2'
services:
  osm_db:
    command: postgres -N 512 --max_wal_size=250MB
  osm_importer:
    environment:
      - ram_cache=200  # in megabytes
      - num_processes=4
      - osmupdate_extra_params=--base-url=download.geofabrik.de/europe/switzerland-updates/
      - osm_planet_mirror=http://download.geofabrik.de/
      - osm_planet_path_relative_to_mirror=europe/switzerland-latest.osm.pbf
