version: '2'
services:
  ##### frontend START ########
  osmaxx-proxy:
    image: geometalab/osmaxx-nginx:v3.7.3
    expose:
      - "80"
    volumes:
      - frontend-media:/data/frontend/media
    depends_on:
      - frontend
    networks:
      - osmaxx-internal
      - proxy-tier
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  frontend:
    image: geometalab/osmaxx-frontend:v3.7.3
    command: [honcho, -f, ./web_frontend/Procfile.django.prod, start]
    expose:
      - "8000"
    volumes:
      - frontend-data:/data
      - frontend-results:/results
      - frontend-media:/data/media
      - worker-data:/data/media/job_result_files
    links:
      - frontenddatabase:database
      - mediator:conversion-service
      - conversionserviceredis:redis
    env_file:
      - base.env
      - frontend.env
    environment:
      - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - NUM_WORKERS=5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - frontenddatabase
      - mediator
    networks:
      - osmaxx-internal
      - proxy-tier
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  frontenddatabase:
    image: geometalab/postgis:9.4
    volumes:
      - frontend-database-data:/database/data
    environment:
      - PGDATA=/database/data
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  ##### frontend END ########
  ##### CONVERSION SERVICE START ########
  mediator:
    image: geometalab/osmaxx-mediator:v3.7.3
    command: [honcho, -f, ./osmaxx_conversion_service/Procfile.mediator.prod, start]
    expose:
      - "8901"
    volumes:
      - worker-data:/data/media/job_result_files
    links:
      - conversionserviceredis:redis
      - mediatordatabase:database
    env_file:
      - base.env
      - conversion.env
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NUM_WORKERS=5
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=osmaxx_conversion_service.config.settings.production
    depends_on:
      - conversionserviceredis
      - mediatordatabase
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  worker:
    image: geometalab/osmaxx-worker:v3.7.3
    command: [honcho, -f, ./osmaxx_conversion_service/Procfile.worker, start]
    volumes:
      - osm_data:/var/data/osm-planet
      - worker-data:/data/media/job_result_files
    links:
      - conversionserviceredis:redis
    external_links:
      - coast_land_sea_database:osmboundaries-database
    env_file:
      - base.env
      - conversion.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=osmaxx_conversion_service.config.settings.worker
    depends_on:
      - conversionserviceredis
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  worker-exclusive:
    image: geometalab/osmaxx-worker:v3.7.3
    command: [honcho, -f, ./osmaxx_conversion_service/Procfile.worker, start]
    volumes:
      - osm_data:/var/data/osm-planet
      - worker-data:/data/media/job_result_files
    links:
      - conversionserviceredis:redis
    external_links:
      - coast_land_sea_database:osmboundaries-database
    env_file:
      - base.env
      - conversion.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=osmaxx_conversion_service.config.settings.worker
      # only listens for jobs in this specific queue
      - WORKER_QUEUES=high
    depends_on:
      - conversionserviceredis
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  conversionserviceredis:
    image: redis
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  mediatordatabase:
    image: geometalab/postgis:9.4
    volumes:
      - mediator-database-data:/database/data
    environment:
      - PGDATA=/database/data
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  ##### CONVERSION SERVICE END ########
  ##### WORLD PBF UPDATER START ########
  osm-pbf-updater:
    # to limit scaling to exactly 1, we need to specify the container name
    container_name: osm-pbf-updater
    image: geometalab/osm-pbf-updater:v3.7.3
    volumes:
      - osm_data:/var/data/osm-planet
    logging:
      driver: "json-file"
      options:
        max-size: 1M
  ##### WORLD PBF UPDATER END ########
  ##### BOUNDARIES START ########
  coast_land_sea_database:
    # to limit scaling to exactly 1, we need to specify the container name
    container_name: coast_land_sea_database
    image: geometalab/postgis:9.5
    volumes:
      - coast_land_sea_database-data:/var/lib/postgresql/data/
    command: postgres -B 2GB -F -N 512 -S 2GB
    environment:
      - POSTGRES_DB=osmboundaries
      - POSTGRES_USER=osmboundaries
      - POSTGRES_PASSWORD=osmboundaries
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
    restart: always
  coast_land_sea_importer:
    # to limit scaling to exactly 1, we need to specify the container name
    container_name: coast_land_sea_importer
    image: geometalab/osmboundaries:latest
    depends_on:
      - coast_land_sea_database
    links:
      - coast_land_sea_database:osmboundaries-database
    environment:
        # the same as the ones in the database above
        - POSTGRES_DB=osmboundaries
        - POSTGRES_USER=osmboundaries
        - POSTGRES_PASSWORD=osmboundaries
        # same as the link name/depends_on
        - POSTGRES_HOST=osmboundaries-database
    networks:
      - osmaxx-internal
    logging:
      driver: "json-file"
      options:
        max-size: 1M
##### BOUNDARIES END ########
volumes:
  # osmaxx
  frontend-database-data: {}
  frontend-data: {}
  frontend-media: {}
  frontend-results: {}
  mediator-database-data: {}
  worker-data: {}
  osm_data: {}
  coast_land_sea_database-data: {}
networks:
  osmaxx-internal: {}
  proxy-tier:
    external:
      name: nginx-proxy
